### ISSUE TITLE
Change port & register with prometheus

### ISSUE THREAD

**Issue by andrewlow** [prg3/ted5000_exporter#1]
Thank you for building a TED5000 prometheus exporter.

The port you've used overlaps with the apache port - not a big deal, but it'd help visibility of your work and conflict with running it to register with the prometheus project

https://github.com/prometheus/prometheus/wiki/Default-port-allocations

It also appears there is a dockerhub build of your work, unclear if this is you or someone else. Still that appears useful and might be something you link in the README (apologies for lumping two issues together).

**Comment by prg3** [comment]
Hey Andrew.. I can absolutely do that. 

https://github.com/prg3/ted5000_exporter/commit/e902479cf5a90c01181d1fc37f36e8611265a37a
and
https://github.com/prg3/ted5000_exporter/commit/6634342d773d764c0572160c1cd6b1f4b02d5434

And registered that port on the Wiki!

Thanks for pointing this out!

**Comment by andrewlow** [comment]
👍
